# Generated by Django 4.2 on 2023-04-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=25)),
                ('p_description', models.CharField(blank=True, max_length=152, null=True)),
                ('p_quantity', models.IntegerField()),
                ('p_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('p_instock', models.BooleanField()),
            ],
        ),
    ]
