# Generated by Django 4.2 on 2023-04-26 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
